# Generated by Django 4.2.6 on 2023-10-21 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('doc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_title', models.CharField(max_length=100)),
                ('doc_text', models.TextField()),
                ('doc_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocSection',
            fields=[
                ('doc_section_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_section_title', models.CharField(max_length=100)),
                ('doc_section_text', models.TextField()),
                ('doc_section_date', models.DateTimeField(auto_now_add=True)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.doc')),
            ],
        ),
    ]
